//Ver parciales
describe('ver parciales', () => {
    it('passes', () => {
      cy.visit('http://127.0.0.1:8000')
      cy.wait(1000)
      cy.get('#matricula').type('00')
      cy.get('#password').type('Prueba')
      cy.get('.text-white').click()
      cy.wait(1000)
      cy.get(':nth-child(7) > .flex').click()
      cy.wait(1000)
    })
  }) 

//Agregar parcial
describe('agregar parcial', () => {
    it('passes', () => {
      cy.visit('http://127.0.0.1:8000')
      cy.wait(1000)
      cy.get('#matricula').type('00')
      cy.get('#password').type('Prueba')
      cy.get('.text-white').click()
      cy.wait(1000)
      cy.get(':nth-child(7) > .flex').click()
      cy.wait(1000)
      cy.get('.flex-col > .text-white').click()
      cy.wait(1000)
      cy.get(':nth-child(1) > #abbreviation').type('DTS')
      cy.wait(1000)
      cy.get(':nth-child(2) > #fullName').type('Primer Parcial 1er Semestre DTS')
      cy.wait(1000)
      cy.get('#datepicker-create-range-start').click()
      cy.wait(1000)
      cy.get('#datepicker-create-range-start').type('2024-02-12')
      cy.wait(1000)
      cy.get('#datepicker-create-range-end').click()
      cy.wait(1000)
      cy.get('#datepicker-create-range-end').type('2024-06-01')
      cy.wait(1000)
      cy.get('#midterms-create-modal > .max-w-md > .bg-white > form.p-4 > .mt-4').click()
      cy.wait(1000)
      cy.get('#simple-search').click()
      cy.wait(1000)
      cy.get('#simple-search').type('Primer Parcial 1er Semestre DTS')
      cy.wait(1000)
      cy.get('#simple-search').focus().type('{enter}')
      cy.wait(1000)
    })
  })

  //Agregar parcial con datos incorrectos

  describe('agregar incorrecto', () => {
    it('passes', () => {
      cy.visit('http://127.0.0.1:8000')
      cy.wait(1000)
      cy.get('#matricula').type('00')
      cy.get('#password').type('Prueba')
      cy.get('.text-white').click()
      cy.wait(1000)
      cy.get(':nth-child(7) > .flex').click()
      cy.wait(1000)
      cy.get('.flex-col > .text-white').click()
      cy.wait(1000)
      cy.get(':nth-child(1) > #abbreviation').type('IMK1')
      cy.wait(1000)
      cy.get(':nth-child(2) > #fullName').type('Primer Parcial 1er Semestre IMK')
      cy.wait(1000)
      cy.get('#datepicker-create-range-start').click()
      cy.wait(1000)
      cy.get('#datepicker-create-range-start').type('2024-04-12')
      cy.wait(1000)
      cy.get('#datepicker-create-range-end').click()
      cy.wait(1000)
      cy.get('#datepicker-create-range-end').type('2024-05-01')
      cy.wait(1000)
      cy.get('#midterms-create-modal > .max-w-md > .bg-white > form.p-4 > .mt-4').click()
      cy.wait(1000)
      cy.get ('[role="alert"]').should("contain.text", "The abbreviation field must not be greater than 3 characters.")
    })
  })

  //Actualizar Parcial

  describe('actualizar parcial', () => {
    it('passes', () => {
      cy.visit('http://127.0.0.1:8000')
      cy.wait(1000)
      cy.get('#matricula').type('00')
      cy.get('#password').type('Prueba')
      cy.get('.text-white').click()
      cy.wait(1000)
      cy.get(':nth-child(7) > .flex').click()
      cy.wait(1000)
      cy.get(':nth-child(6) > .py-3').click()
      cy.wait(1000)
      cy.get('#DTS-2024-02-12-2024-06-01-dropdown > .py-1.text-sm > li > .block').click()
      cy.wait(1000)
      cy.get('#midterms-DTS-2024-02-12-2024-06-01-edit-modal > .max-w-md > .bg-white > form.p-4 > .grid > :nth-child(3) > #fullName').clear()
      cy.wait(1000)
      cy.get('#midterms-DTS-2024-02-12-2024-06-01-edit-modal > .max-w-md > .bg-white > form.p-4 > .grid > :nth-child(3) > #fullName').type('2do Parcial de DTS Primer Semestre')
      cy.wait(1000)
      cy.get('#midterms-DTS-2024-02-12-2024-06-01-edit-modal > .max-w-md > .bg-white > form.p-4 > .mt-4').click()
      cy.wait(1000)
      cy.get('#simple-search').click()
      cy.wait(1000)
      cy.get('#simple-search').type('2do Parcial de DTS Primer Semestre')
      cy.wait(1000)
      cy.get('#simple-search').focus().type('{enter}')
      cy.wait(1000)
    })
  })

  //Actualizar parcial incorrecto

  describe('actualizar incorrecto', () => {
    it('passes', () => {
      cy.visit('http://127.0.0.1:8000')
      cy.wait(1000)
      cy.get('#matricula').type('00')
      cy.get('#password').type('Prueba')
      cy.get('.text-white').click()
      cy.wait(1000)
      cy.get(':nth-child(7) > .flex').click()
      cy.wait(1000)
      cy.get(':nth-child(6) > .py-3').click()
      cy.wait(1000)
      cy.get('#DTS-2024-02-12-2024-06-01-dropdown > .py-1.text-sm > li > .block').click()
      cy.wait(1000)
      cy.get('#midterms-DTS-2024-02-12-2024-06-01-edit-modal > .max-w-md > .bg-white > form.p-4 > .grid > :nth-child(2) > #abbreviation').clear()
      cy.wait(1000)
      cy.get('#midterms-DTS-2024-02-12-2024-06-01-edit-modal > .max-w-md > .bg-white > form.p-4 > .grid > :nth-child(2) > #abbreviation').type('DTS1')
      cy.wait(1000)
      cy.get('#midterms-DTS-2024-02-12-2024-06-01-edit-modal > .max-w-md > .bg-white > form.p-4 > .mt-4').click()
      cy.wait(1000)
      cy.get ('[role="alert"]').should("contain.text", "The abbreviation field must not be greater than 3 characters.")
    })
  })

  //Eliminar parcial
  describe('eliminar parcial', () => {
    it('passes', () => {
      cy.visit('http://127.0.0.1:8000')
      cy.wait(1000)
      cy.get('#matricula').type('00')
      cy.get('#password').type('Prueba')
      cy.get('.text-white').click()
      cy.wait(1000)
      cy.get(':nth-child(7) > .flex').click()
      cy.wait(1000)
      cy.get(':nth-child(6) > .py-3').click()
      cy.wait(1000)
      cy.get('#DTS-2024-02-12-2024-06-01-dropdown > div.py-1 > form > .block').click()
      cy.wait(1000)
      cy.get('#simple-search').click()
      cy.wait(1000)
      cy.get('#simple-search').type('2do Parcial de DTS Primer Semestre')
      cy.wait(1000)
      cy.get('#simple-search').focus().type('{enter}')
      cy.wait(1000)
    })
  })

  //Buscar Parcial
  describe('buscar parcial', () => {
    it('passes', () => {
      cy.visit('http://127.0.0.1:8000')
      cy.wait(1000)
      cy.get('#matricula').type('00')
      cy.get('#password').type('Prueba')
      cy.get('.text-white').click()
      cy.wait(1000)
      cy.get(':nth-child(7) > .flex').click()
      cy.wait(1000)
      cy.get('#simple-search').click()
      cy.wait(1000)
      cy.get('#simple-search').type('autem placeat consequatur')
      cy.wait(1000)
      cy.get('#simple-search').focus().type('{enter}')
      cy.wait(1000)
    })
  })

  //Filtro de desactivado
  describe('filtro desactivado', () => {
    it('passes', () => {
      cy.visit('http://127.0.0.1:8000')
      cy.wait(1000)
      cy.get('#matricula').type('00')
      cy.get('#password').type('Prueba')
      cy.get('.text-white').click()
      cy.wait(1000)
      cy.get(':nth-child(7) > .flex').click()
      cy.wait(1000)
      cy.get('#filterDropdownButton').click()
      cy.get('#filterDropdown > .space-y-2 > .flex').click()
      cy.get('#simple-search').click()
      cy.wait(1000)
      cy.get('#simple-search').focus().type('{enter}')
      cy.wait(1000)
    })
  }) 

  //reactivar parcial

  describe('reactivar parcial', () => {
    it('passes', () => {
      cy.visit('http://127.0.0.1:8000')
      cy.wait(1000)
      cy.get('#matricula').type('00')
      cy.get('#password').type('Prueba')
      cy.get('.text-white').click()
      cy.wait(1000)
      cy.get(':nth-child(7) > .flex').click()
      cy.wait(1000)
      cy.get('#filterDropdownButton').click()
      cy.wait(1000)
      cy.get('#filterDropdown > .space-y-2 > .flex').click()
      cy.wait(1000)
      cy.get('#simple-search').click()
      cy.wait(1000)
      cy.get('#simple-search').focus().type('{enter}')
      cy.wait(1000)
      cy.get('#DTS-2024-02-12-2024-06-01-dropdown-button > .w-5').click()
      cy.wait(1000)
      cy.get('form > .block').click()
      cy.wait(1000)
      cy.get ('[role="alert"]').should("contain.text", "Midterm DTS-2024-02-12-2024-06-01 has been restored")
    })
  }) 

